Feature/button
isdi-coders-2023/coding-adventure-Alex-Navarro-front-202301-BCN pull request #1
Opened 2023-02-27 15:39 UTC by alexnavter

2023-02-27 16:01 UTC, MMLORENA submitted a review, later dismissed
Debería haber unas variables de css o usar el theme provider para no repetir las fuentes y colores a lo largo del diseño

2023-02-27 16:01 UTC, MMLORENA commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One", sans-serif;
¿Por qué le has vuelto a poner la font-family?

2023-02-27 16:06 UTC, alexnavter commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One", sans-serif;
La acabo de borrar de Global y solo la especifico en el botón ahora.

2023-02-27 16:26 UTC, MMLORENA commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One", sans-serif;
En principio en este caso debería ser al revés, ya lo habías hecho correctamente en el GlobalStyles. El que sobraba era el del ButtonStyled.

2023-02-27 16:34 UTC, alexnavter commented
[X] Create Button component
[X] Test Button component
[X] Add Global Styles

2023-02-27 16:35 UTC, alexnavter commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One", sans-serif;
Hecho 😊

2023-02-27 16:37 UTC, MMLORENA commented
@alexnavter Ya tienes un test, elimina del script el passWithNoTest

2023-02-27 16:47 UTC, alexnavter commented
Done !

2023-02-27 17:33 UTC, MMLORENA commented on src/components/App/App.tsx
> +      <Button text="Sign up" />
No lo pedía el enunciado que se renderizara Button en App

2023-02-28 10:50 UTC, alexnavter commented on src/components/App/App.tsx
> +      <Button text="Sign up" />
Solucionado

2023-02-28 10:52 UTC, alexnavter commented on src/components/Button/ButtonStyled.tsx
> +    height: 57px;
Solucionado

2023-02-28 11:13 UTC, alexnavter commented
@MMLORENA @benjaminrae

2023-02-28 11:38 UTC, benjaminrae requested changes

2023-02-28 11:38 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Hay que sacar los colores a otro sitio y otro css que se repite

2023-02-28 11:43 UTC, alexnavter commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Solucionado

2023-02-28 11:43 UTC, benjaminrae approved these changes
Sigue con el formulario

2023-02-28 11:45 UTC, alexnavter commented
Haleluya !

2023-02-28 11:45 UTC, merged