Add styles to RegisterForm component
isdi-coders-2023/coding-adventure-Alex-Navarro-front-202301-BCN pull request #3
Opened 2023-02-28 12:56 UTC by alexnavter

2023-02-28 13:06 UTC, MMLORENA requested changes

2023-02-28 13:06 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
>          <div className="label-container">
¿Solo incluyes a un label en ese div?

2023-02-28 13:06 UTC, MMLORENA commented on src/components/RegisterForm/RegisterFormStyled.tsx
> +const RegisterFormStyled = styled.form`
Esto no iba en está FASE 🤣

2023-02-28 13:07 UTC, MMLORENA requested changes
Has juntado fases. El style del form no iba aquí. Te paso el enunciado:
Dale estilos al formulario (no dar estilo al input type file).

2023-02-28 13:07 UTC, MMLORENA commented on src/components/RegisterForm/RegisterFormStyled.tsx
> +    margin-bottom: -25px;
Nooooooooo ☠, margin-bottom negativoooooo para centrar algo

2023-02-28 14:18 UTC, alexnavter commented on src/components/RegisterForm/RegisterForm.tsx
>          <div className="label-container">
Solucionado.

2023-02-28 14:18 UTC, alexnavter commented on src/components/RegisterForm/RegisterFormStyled.tsx
> +const RegisterFormStyled = styled.form`
Siiii

2023-03-01 14:48 UTC, alexnavter commented
@benjaminrae

2023-03-02 10:46 UTC, MMLORENA commented on src/components/RegisterForm/RegisterForm.tsx
> +        <div className="form__container">
Este contenedor no necesita aplicar BEM porque no es un elemento del bloque.

2023-03-02 10:46 UTC, MMLORENA commented on src/components/styles/GlobalStyles.tsx
> +  height: 100vh;
No usamos el body como contenedor

2023-03-02 10:49 UTC, MMLORENA approved these changes
Testea el componente formulario (responsabilidad de mostrar).

2023-03-02 11:14 UTC, alexnavter commented
Thanks.

2023-03-02 11:14 UTC, merged

2023-03-02 11:14 UTC, alexnavter commented on src/components/RegisterForm/RegisterForm.tsx
> +        <div className="form__container">
Done.